[package]
name = "rosella-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { git = "https://github.com/hYdos/ash" }
ash-window = { git = "https://github.com/hYdos/ash" }
gpu-allocator = "0.11.0"
nalgebra = "0.29.0"
shaderc = "0.7.3"
topological-sort = { version = "0.1.0" }
twox-hash = "1.6.1"
winit = { version = "0.25.0" }
